easy_admin:
    list:
        batch_actions: [{ name: 'delete', ask_confirm: true }]
    user:
        name_property_path: 'firstname'
    entities:
        Tourists:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - { property: 'email', type: 'email' }
                    - firstName
                    - lastName
                    - age
                    - {property: 'city.name', label: 'City'}
                    - availStartDate
                    - availEndDate
                    - {property: 'isTourist', label: 'Tourist'}
                    - {property: 'isTutor', label: 'Local'}
                    - meetupType

                dql_filter: 'entity.isTourist = true'
                actions:
                    - {name: 'show', icon: 'search-plus', label: false, css_class: 'btn btn-info'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-success'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}

            form:
                title: 'Add a Tourist'
                fields:
                    - { type: 'section', label: 'User Details' }
                    - email
                    - {property: 'firstName', type: 'text'}
                    - {property: 'lastName', type: 'text'}
                    - age
                    - city
                    - { type: 'section', label: 'Meetup Details' }
                    - {property: 'availStartDate', label: 'Available Start Date'}
                    - availEndDate
                    - isTourist
                    - isTutor
                    - meetupType
                    - publicMessage
                new:
                    -'-id'

                edit:
                    title:  'Edit a Tourist'
            show:
                fields:
                    - id
                    - { property: 'email', type: 'email' }
                    - firstName
                    - lastName
                    - age
                    - {property: 'city.name', label: 'City'}
                    - {property: 'availStartDate', label: 'Available Start Date'}
                    - {property: 'availEndDate', label: 'Available End Date'}
                    - isTourist
                    - isTutor
                    - meetupType
                    - publicMessage

        Locals:
            class: App\Entity\User
            list:
                dql_filter: 'entity.isTutor = true'
                actions:
                    - {name: 'show', icon: 'search-plus', label: false, css_class: 'btn btn-info'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-success'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
                fields:
                    - id
                    - { property: 'email', type: 'email' }
                    - firstName
                    - lastName
                    - age
                    - {property: 'city.name', label: 'City'}
                    - availStartDate
                    - availEndDate
                    - {property: 'isTourist', label: 'Tourist'}
                    - {property: 'isTutor', label: 'Local'}
                    - meetupType
            form:
                title: 'Add a Local'
                fields:
                    - { type: 'section', label: 'User Details' }
                    - email
                    - {property: 'firstName', type: 'text'}
                    - {property: 'lastName', type: 'text'}
                    - age
                    - city
                    - { type: 'section', label: 'Meetup Details' }
                    - availStartDate
                    - availEndDate
                    - {property: 'isTourist', label: 'Tourist'}
                    - {property: 'isTutor', label: 'Local'}
                    - meetupType
                    - publicMessage
                new:
                    -'-id'

                edit:
                    title:  'Edit a Local'
            show:
                fields:
                    - id
                    - { property: 'email', type: 'email' }
                    - firstName
                    - lastName
                    - age
                    - {property: 'city.name', label: 'City'}
                    - {property: 'availStartDate', label: 'Available Start Date'}
                    - {property: 'availEndDate', label: 'Available End Date'}
                    - {property: 'isTourist', label: 'Tourist'}
                    - {property: 'isTutor', label: 'Local'}
                    - meetupType
                    - publicMessage
        User:
            class: App\Entity\User
            help: ''
            label: 'Users'
            list:
                fields: ['id', 'email', 'firstName', 'lastName', 'age', 'city.name', 'availStartDate', 'availEndDate', 'isTourist', 'isTutor', 'meetupType']

                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            show:
            search:


        City:
            class: App\Entity\City
            label: 'Cities'
            list:
                fields:
                    ['id', 'name', 'country.name', 'users', 'meetups']
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: 'Add a City'
                fields:
                    - name
                    - country

                new:

                edit:
                    title:  'Edit a City'


        Comment:
            disabled_actions: ['new']
            class: App\Entity\Comment
            label: 'Comments'
            list:
                fields:
                  ['id', 'text', 'commentAuthor', 'commentRecipient', 'createdAt']
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}



        Country:
            class: App\Entity\Country
            label: 'Countries'
            list:
                fields:
                  ['id', 'name', 'cities']
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: 'Add a Country'
                fields:
                    - name
                new:
                edit:
                    title:  'Edit a Country'


        Image:

            class: App\Entity\Image
            label: 'Images'
            list:
                fields:
                    - id
                    - {property: 'user.fullname', label: 'User'}
                    - {property: 'user.email', label: 'User Email'}
                    - filename
                    - title
                    - caption
                    - createdAt
                    - { property: 'image', type: 'image', base_path: '%uploads_path%' }

                actions:
                    - {name: 'show', icon: 'search-plus', label: false, css_class: 'btn btn-info'}
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-success'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: 'Add an Image'
                form:
                    fields:
                        - user.email
                        - filename
                        - title
                        - caption
                        - createdAt
                        - {property: 'imageFile', type: 'vich_image', label: 'Profile photo'}

                new:
                    fields:
                        - user.id
                        - filename
                        - title
                        - caption
                        - createdAt
                        - {property: 'imageFile', type: 'vich_image', label: 'Profile photo'}


                edit:
                    title:  'Edit an Image'
                    fields:
                        - user.id
                        - filename
                        - title
                        - caption
                        - createdAt
                        - {property: 'imageFile', type: 'vich_image', label: 'Profile photo'}


        Meetup:
            disabled_actions: ['new']
            class: App\Entity\Meetup
            label: 'Meetups'
            list:
                fields:
                  ['id', 'name', 'date', 'startTime', 'endTime', 'type', 'description', 'city', 'users']
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            form:
                title: 'Add a Meetup'

                new:

                edit:
                    title:  'Edit a Meetup'

        Message:
            disabled_actions: ['new']
            class: App\Entity\Message
            label: 'Messages'

            list:
                fields:
                  ['id', 'subject', 'text', 'messageAuthor', 'messageRecipient', 'createdAt']
                title: ""
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
        Language:
            disabled_actions: ['new']
            class: App\Entity\Language
            label: 'Languages'

            list:
                fields:
                  ['id', 'name']
                title: ""
                actions:
                    - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
                    - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}


    site_name: 'Colloq'
    design:
        brand_color: '#ff7043'
        assets:
            css:
                # ...
                - 'css/admin.css'
        menu:
            - label: "Users"
              icon: 'user'
              children: ['Tourists', 'Locals']
            - label: "User Profile"
              icon: 'address-card'
              children: ['Comment', 'Message', 'Image', 'Language']
            - label: 'Location'
              icon: 'globe-americas'
              children: ['City', 'Country']
            - label: 'Events'
              icon: 'comments'
              children: ['Meetup']
            - { label: 'Api', url: '/api', icon: 'table' }
            - { label: 'Colloq App', url: 'http://localhost:3000', icon: 'asterisk'}
