vich_uploader:
    db_driver: orm

    mappings:
        profile_photos:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/../%uploads_path%'
#            namer: Vich\UploaderBundle\Naming\OrignameNamer