#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_test:
  path:     /api/login_check
  methods:  [POST]

register:
  path: /api/register
  controller: App\Controller\AuthController::register
  methods: POST